FROM node:16

# Instalamos Python 3.10 y pip
RUN apt update \
    && apt install -y python3.10 python3-pip

# Establecemos el directorio de trabajo
WORKDIR /opt/app

# Copiamos los archivos del proyecto
COPY . /app/

# Creamos un entorno virtual y activamos el entorno
RUN python3 -m venv /opt/app/venv

# Instalamos las dependencias del archivo requirements.txt
RUN /opt/app/venv/bin/pip install -r /app/requirements.txt  # Asegúrate de tener el archivo requirements.txt

# Aseguramos que el entorno virtual esté disponible en el PATH
ENV PATH="/opt/app/venv/bin:$PATH"

# Establecemos NODE_ENV para contenedores
ENV NODE_ENV=container

# Fase de release (si es necesario, copiamos otros archivos de configuración)
COPY --from=build /opt/app/venv /venv
