FROM node:16

# Instalamos python3.10, pip y pipenv
RUN apt update \
    && apt install -y python3.10 python3-pip \
    && pip3 install --upgrade pip \
    && pip3 install pipenv  # Instalamos pipenv globalmente

# Establecemos el directorio de trabajo
WORKDIR /opt/app

# Copiamos los archivos necesarios
COPY . /app/

# Instalamos las dependencias de pipenv en la fase de construcción
RUN pipenv install --deploy --ignore-pipfile  # Esto instalará las dependencias

# Aseguramos que pipenv esté disponible en el PATH
ENV PATH="/opt/app/.venv/bin:$PATH"
ENV NODE_ENV=container

# Fase de release (si es necesario, copia otros archivos de configuración)
COPY --from=build /opt/app
