FROM node:16

# Instalamos python3.10 y pip
RUN apt update \
    && apt install -y software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt update \
    && apt install -y python3.10 python3-pip \
    && pip3 install --upgrade pip \
    && pip3 install pipenv  # Instalamos pipenv globalmente

# Establecemos el directorio de trabajo
WORKDIR /opt/app

# Copiamos los archivos necesarios
COPY --from=build /opt/app/venv /venv

# Aseguramos que pipenv esté disponible en el PATH
ENV PATH="/opt/app/venv/bin:$PATH"
ENV NODE_ENV=container

# Instalamos las dependencias de pipenv en la fase de construcción
RUN pipenv install --deploy --ignore-pipfile  # Instala las dependencias directamente
